FROM python:3
COPY requirements.txt /
RUN pip install -r requirements.txt

ARG VERSION
COPY dist/univariate_linear_regression-${VERSION}.tar.gz /
ARG VERSION
RUN pip install /univariate_linear_regression-${VERSION}.tar.gz
WORKDIR /app
CMD ulr
